#pragma once
// ==== owsprite ====
// Where every overworld prop sits in assets/ow_props.png, in whole tiles.
// GENERATED by tools/build_overworld_sheets.py - edit the PROPS table there
// and re-run, never this file. Each frame's trunk is on its centre line and
// its base on its bottom edge, so grid::standingOn(frame, x, y) roots it on
// tile (x, y).

namespace owsprite {

// wetRow: the row of ow_props_wet.png holding the frame's submerged
// bottom row, at the same columns.
struct Frame {
  int col, row, w, h, wetRow;
};

enum Id : int {
  OAK_AUTUMN_A,
  OAK_AUTUMN_B,
  OAK_SUMMER_A,
  OAK_SUMMER_B,
  OAK_WINTER_A,
  OAK_WINTER_B,
  OAK_BARE_A,
  OAK_BARE_B,
  BIRCH_AUTUMN_A,
  BIRCH_AUTUMN_B,
  BIRCH_SUMMER_A,
  BIRCH_SUMMER_B,
  BIRCH_WINTER_A,
  BIRCH_WINTER_B,
  BIRCH_BARE_A,
  BIRCH_BARE_B,
  FIR_0,
  FIR_1,
  FIR_2,
  FIR_3,
  FIR_4,
  FIR_DARK_0,
  FIR_DARK_1,
  FIR_DARK_2,
  FIR_DARK_3,
  PC1_S2_GREEN,
  PC1_S2_TAN,
  PC1_S2_BARE,
  PC1_S2_FROZEN,
  PC1_S2_ORANGE,
  PC1_S2_AMBER,
  PC1_S3_GREEN,
  PC1_S3_TAN,
  PC1_S3_BARE,
  PC1_S3_FROZEN,
  PC1_S3_ORANGE,
  PC1_S3_AMBER,
  PC1_S4_GREEN,
  PC1_S4_TAN,
  PC1_S4_BARE,
  PC1_S4_FROZEN,
  PC1_S4_ORANGE,
  PC1_S4_AMBER,
  PC1_S5_GREEN,
  PC1_S5_TAN,
  PC1_S5_BARE,
  PC1_S5_FROZEN,
  PC1_S5_ORANGE,
  PC1_S5_AMBER,
  PC2_S2_TEAL,
  PC2_S2_TEAL_B,
  PC2_S2_GREEN,
  PC2_S2_GREEN_B,
  PC2_S3_TEAL,
  PC2_S3_TEAL_B,
  PC2_S3_BARE,
  PC2_S3_GREEN,
  PC2_S3_GREEN_B,
  PC2_S4_TEAL,
  PC2_S4_TEAL_B,
  PC2_S4_BARE,
  PC2_S4_GREEN,
  PC2_S4_GREEN_B,
  PC2_S5_TEAL,
  PC2_S5_TEAL_B,
  PC2_S5_BARE,
  PC2_S5_GREEN,
  PC2_S5_GREEN_B,
  PC3_S2_GREEN,
  PC3_S2_OLIVE,
  PC3_S2_TAN,
  PC3_S2_RUST,
  PC3_S3_GREEN,
  PC3_S3_OLIVE,
  PC3_S3_TAN,
  PC3_S3_RUST,
  PC3_S3_BARE,
  PC3_S4_GREEN,
  PC3_S4_OLIVE,
  PC3_S4_TAN,
  PC3_S4_RUST,
  PC3_S4_BARE,
  PC3_S5_GREEN,
  PC3_S5_OLIVE,
  PC3_S5_TAN,
  PC3_S5_RUST,
  PC3_S5_BARE,
  WILLOW_LIT,
  WILLOW,
  WILLOW_S_A,
  WILLOW_S_B,
  WILLOW_S_C,
  PALM_TALL,
  PALM_SHORT,
  BUSH_A,
  BUSH_B,
  BUSH_C,
  BUSH_D,
  BUSH_LOW,
  BUSH_SMALL,
  ROCK_GREY_0,
  ROCK_GREY_1,
  ROCK_GREY_2,
  ROCK_GREY_3,
  ROCK_GREY_4,
  ROCK_GREY_BIG,
  ROCK_MOSS_1,
  ROCK_MOSS_2,
  ROCK_MOSS_3,
  BOULDER_BROWN,
  BOULDER_BROWN_LOW,
  BOULDER_GREY,
  BOULDER_GREY_LOW,
  CATTAIL_TALL,
  CATTAIL_SHORT,
  SWAMP_PLANT,
  DECAL_FLOWERS_A,
  DECAL_FLOWERS_B,
  DECAL_FLOWER,
  DECAL_STARS_A,
  DECAL_STARS_B,
  DECAL_TUFT_A,
  DECAL_TUFT_B,
  DECAL_PATCH_A,
  DECAL_PATCH_B,
  DECAL_PATCH_C,
  DECAL_TWIGS,
  DECAL_FERN,
  DECAL_MUSHROOM_RED,
  DECAL_MUSHROOM_BROWN,
  DECAL_MUSHROOMS,
  DECAL_PEBBLE_GREY,
  DECAL_PEBBLES_GREY,
  DECAL_PEBBLE_MOSS,
  DECAL_PEBBLE_BROWN,
  DECAL_STONE_WATER_A,
  DECAL_STONE_WATER_B,
  DECAL_STONE_WATER_C,
  DECAL_STONE_WATER_MOSS,
  DECAL_DEAD_TUFT_A,
  DECAL_DEAD_TUFT_B,
  DECAL_ICE_A,
  DECAL_ICE_B,
  DECAL_SHELL,
  DECAL_SHELL_PINK,
  COUNT
};

// The tallest frame, in tiles: how far below the screen a prop can be
// rooted and still reach into view.
inline constexpr int kTallestTiles = 16;

inline constexpr Frame kFrames[COUNT] = {
    {10, 69, 6, 7, 6}, // OAK_AUTUMN_A
    {16, 69, 5, 7, 6}, // OAK_AUTUMN_B
    {21, 69, 6, 7, 6}, // OAK_SUMMER_A
    {27, 69, 5, 7, 6}, // OAK_SUMMER_B
    {32, 69, 6, 7, 6}, // OAK_WINTER_A
    {0, 77, 5, 7, 7}, // OAK_WINTER_B
    {32, 77, 5, 6, 7}, // OAK_BARE_A
    {0, 84, 5, 6, 8}, // OAK_BARE_B
    {24, 52, 5, 8, 4}, // BIRCH_AUTUMN_A
    {29, 52, 5, 8, 4}, // BIRCH_AUTUMN_B
    {34, 52, 5, 8, 4}, // BIRCH_SUMMER_A
    {0, 61, 5, 8, 5}, // BIRCH_SUMMER_B
    {5, 61, 5, 8, 5}, // BIRCH_WINTER_A
    {10, 61, 5, 8, 5}, // BIRCH_WINTER_B
    {5, 84, 5, 6, 8}, // BIRCH_BARE_A
    {10, 84, 5, 6, 8}, // BIRCH_BARE_B
    {0, 52, 5, 9, 4}, // FIR_0
    {15, 61, 5, 8, 5}, // FIR_1
    {5, 77, 4, 7, 7}, // FIR_2
    {15, 84, 4, 6, 8}, // FIR_3
    {4, 96, 3, 4, 10}, // FIR_4
    {9, 77, 7, 7, 7}, // FIR_DARK_0
    {19, 84, 4, 6, 8}, // FIR_DARK_1
    {7, 96, 4, 4, 10}, // FIR_DARK_2
    {35, 96, 3, 3, 10}, // FIR_DARK_3
    {11, 96, 3, 4, 10}, // PC1_S2_GREEN
    {14, 96, 3, 4, 10}, // PC1_S2_TAN
    {38, 96, 2, 3, 10}, // PC1_S2_BARE
    {0, 101, 2, 3, 11}, // PC1_S2_FROZEN
    {17, 96, 3, 4, 10}, // PC1_S2_ORANGE
    {20, 96, 3, 4, 10}, // PC1_S2_AMBER
    {23, 84, 3, 6, 8}, // PC1_S3_GREEN
    {26, 84, 3, 6, 8}, // PC1_S3_TAN
    {29, 84, 3, 6, 8}, // PC1_S3_BARE
    {32, 84, 3, 6, 8}, // PC1_S3_FROZEN
    {35, 84, 3, 6, 8}, // PC1_S3_ORANGE
    {0, 90, 3, 6, 9}, // PC1_S3_AMBER
    {20, 61, 5, 8, 5}, // PC1_S4_GREEN
    {25, 61, 5, 8, 5}, // PC1_S4_TAN
    {30, 61, 5, 8, 5}, // PC1_S4_BARE
    {35, 61, 5, 8, 5}, // PC1_S4_FROZEN
    {0, 69, 5, 8, 6}, // PC1_S4_ORANGE
    {5, 69, 5, 8, 6}, // PC1_S4_AMBER
    {0, 32, 7, 10, 2}, // PC1_S5_GREEN
    {7, 32, 7, 10, 2}, // PC1_S5_TAN
    {14, 32, 7, 10, 2}, // PC1_S5_BARE
    {21, 32, 7, 10, 2}, // PC1_S5_FROZEN
    {28, 32, 7, 10, 2}, // PC1_S5_ORANGE
    {0, 42, 7, 10, 3}, // PC1_S5_AMBER
    {2, 101, 2, 3, 11}, // PC2_S2_TEAL
    {4, 101, 2, 3, 11}, // PC2_S2_TEAL_B
    {6, 101, 2, 3, 11}, // PC2_S2_GREEN
    {8, 101, 2, 3, 11}, // PC2_S2_GREEN_B
    {21, 90, 3, 5, 9}, // PC2_S3_TEAL
    {24, 90, 3, 5, 9}, // PC2_S3_TEAL_B
    {27, 90, 3, 5, 9}, // PC2_S3_BARE
    {30, 90, 3, 5, 9}, // PC2_S3_GREEN
    {33, 90, 3, 5, 9}, // PC2_S3_GREEN_B
    {16, 77, 4, 7, 7}, // PC2_S4_TEAL
    {20, 77, 4, 7, 7}, // PC2_S4_TEAL_B
    {3, 90, 3, 6, 9}, // PC2_S4_BARE
    {24, 77, 4, 7, 7}, // PC2_S4_GREEN
    {28, 77, 4, 7, 7}, // PC2_S4_GREEN_B
    {7, 42, 6, 10, 3}, // PC2_S5_TEAL
    {13, 42, 6, 10, 3}, // PC2_S5_TEAL_B
    {19, 42, 6, 10, 3}, // PC2_S5_BARE
    {25, 42, 6, 10, 3}, // PC2_S5_GREEN
    {31, 42, 6, 10, 3}, // PC2_S5_GREEN_B
    {36, 90, 2, 5, 9}, // PC3_S2_GREEN
    {38, 90, 2, 5, 9}, // PC3_S2_OLIVE
    {0, 96, 2, 5, 10}, // PC3_S2_TAN
    {2, 96, 2, 5, 10}, // PC3_S2_RUST
    {5, 52, 4, 9, 4}, // PC3_S3_GREEN
    {9, 52, 4, 9, 4}, // PC3_S3_OLIVE
    {13, 52, 4, 9, 4}, // PC3_S3_TAN
    {17, 52, 4, 9, 4}, // PC3_S3_RUST
    {21, 52, 3, 9, 4}, // PC3_S3_BARE
    {7, 16, 7, 13, 1}, // PC3_S4_GREEN
    {14, 16, 7, 13, 1}, // PC3_S4_OLIVE
    {21, 16, 7, 13, 1}, // PC3_S4_TAN
    {28, 16, 7, 13, 1}, // PC3_S4_RUST
    {35, 16, 5, 13, 1}, // PC3_S4_BARE
    {0, 0, 9, 16, 0}, // PC3_S5_GREEN
    {9, 0, 9, 16, 0}, // PC3_S5_OLIVE
    {18, 0, 9, 16, 0}, // PC3_S5_TAN
    {27, 0, 9, 16, 0}, // PC3_S5_RUST
    {0, 16, 7, 16, 1}, // PC3_S5_BARE
    {6, 90, 6, 6, 9}, // WILLOW_LIT
    {12, 90, 6, 6, 9}, // WILLOW
    {23, 96, 3, 4, 10}, // WILLOW_S_A
    {26, 96, 3, 4, 10}, // WILLOW_S_B
    {29, 96, 3, 4, 10}, // WILLOW_S_C
    {18, 90, 3, 6, 9}, // PALM_TALL
    {32, 96, 3, 4, 10}, // PALM_SHORT
    {14, 101, 3, 2, 11}, // BUSH_A
    {17, 101, 2, 2, 11}, // BUSH_B
    {19, 101, 3, 2, 11}, // BUSH_C
    {22, 101, 2, 2, 11}, // BUSH_D
    {32, 101, 2, 1, 11}, // BUSH_LOW
    {34, 101, 1, 1, 11}, // BUSH_SMALL
    {35, 101, 1, 1, 11}, // ROCK_GREY_0
    {36, 101, 1, 1, 11}, // ROCK_GREY_1
    {37, 101, 1, 1, 11}, // ROCK_GREY_2
    {38, 101, 1, 1, 11}, // ROCK_GREY_3
    {39, 101, 1, 1, 11}, // ROCK_GREY_4
    {24, 101, 2, 2, 11}, // ROCK_GREY_BIG
    {0, 104, 1, 1, 12}, // ROCK_MOSS_1
    {1, 104, 1, 1, 12}, // ROCK_MOSS_2
    {2, 104, 1, 1, 12}, // ROCK_MOSS_3
    {10, 101, 2, 3, 11}, // BOULDER_BROWN
    {26, 101, 2, 2, 11}, // BOULDER_BROWN_LOW
    {12, 101, 2, 3, 11}, // BOULDER_GREY
    {28, 101, 2, 2, 11}, // BOULDER_GREY_LOW
    {30, 101, 1, 2, 11}, // CATTAIL_TALL
    {31, 101, 1, 2, 11}, // CATTAIL_SHORT
    {3, 104, 2, 1, 12}, // SWAMP_PLANT
    {5, 104, 2, 1, 12}, // DECAL_FLOWERS_A
    {7, 104, 1, 1, 12}, // DECAL_FLOWERS_B
    {8, 104, 1, 1, 12}, // DECAL_FLOWER
    {9, 104, 1, 1, 12}, // DECAL_STARS_A
    {10, 104, 1, 1, 12}, // DECAL_STARS_B
    {11, 104, 2, 1, 12}, // DECAL_TUFT_A
    {13, 104, 2, 1, 12}, // DECAL_TUFT_B
    {15, 104, 1, 1, 12}, // DECAL_PATCH_A
    {16, 104, 1, 1, 12}, // DECAL_PATCH_B
    {17, 104, 1, 1, 12}, // DECAL_PATCH_C
    {18, 104, 1, 1, 12}, // DECAL_TWIGS
    {19, 104, 2, 1, 12}, // DECAL_FERN
    {21, 104, 1, 1, 12}, // DECAL_MUSHROOM_RED
    {22, 104, 1, 1, 12}, // DECAL_MUSHROOM_BROWN
    {23, 104, 2, 1, 12}, // DECAL_MUSHROOMS
    {25, 104, 1, 1, 12}, // DECAL_PEBBLE_GREY
    {26, 104, 1, 1, 12}, // DECAL_PEBBLES_GREY
    {27, 104, 1, 1, 12}, // DECAL_PEBBLE_MOSS
    {28, 104, 1, 1, 12}, // DECAL_PEBBLE_BROWN
    {29, 104, 1, 1, 12}, // DECAL_STONE_WATER_A
    {30, 104, 1, 1, 12}, // DECAL_STONE_WATER_B
    {31, 104, 1, 1, 12}, // DECAL_STONE_WATER_C
    {32, 104, 1, 1, 12}, // DECAL_STONE_WATER_MOSS
    {33, 104, 2, 1, 12}, // DECAL_DEAD_TUFT_A
    {35, 104, 2, 1, 12}, // DECAL_DEAD_TUFT_B
    {37, 104, 1, 1, 12}, // DECAL_ICE_A
    {38, 104, 1, 1, 12}, // DECAL_ICE_B
    {39, 104, 1, 1, 12}, // DECAL_SHELL
    {0, 105, 1, 1, 13}, // DECAL_SHELL_PINK
};

} // namespace owsprite
