#!/usr/bin/env python3
"""Generate everything derived from assets/palette.json: src/core/palette.hpp,
assets/palette_strip.png and assets/palette_swatch.png.

Usage:
    python tools/palette_header.py

Why: the sheets are held to the palette by quantize.py, but the UI, the item
glows and the fade overlays are drawn from C++ colour literals, and a literal
cannot be checked by a PNG tool. This writes the palette as constexpr raylib
Colors so C++ has no reason to spell a hex by hand. Ramps keep their JSON
names and step order (0 = darkest); roles ("text", "alert") are not here -
they are a hand decision and live in ui/ui_theme.hpp.

The strip is one pixel per colour, ramp by ramp (import it into
Aseprite/GIMP as a palette); the swatch is the labelled picture docs/palette.md
shows. Re-run after any change to assets/palette.json and commit all three.
The test PaletteHeader.MatchesStrip fails if header and strip drift.
"""
import json
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "palette.json")
DST = os.path.join(ROOT, "src", "core", "palette.hpp")
STRIP = os.path.join(ROOT, "assets", "palette_strip.png")
SWATCH = os.path.join(ROOT, "assets", "palette_swatch.png")


def draw_swatch(ramps, path):
    """Labelled ramps. Text uses palette colours, but the ground is
    deliberately off-palette (a dull plum no ramp contains) so the darkest
    neutral reads as a block against it. The labels are anti-aliased anyway,
    so quantize.py --check skips this file by name; it is documentation, not
    a sheet the game loads."""
    cell, pad, label_w = 48, 8, 88
    font = ImageFont.load_default()
    by = {r["name"]: r["colours"] for r in ramps}
    ink = tuple(by["neutral"][-1]["rgb"]); dim = tuple(by["neutral"][-3]["rgb"])
    ground = (38, 26, 44)  # off-palette on purpose: see docstring
    width = label_w + max(len(r["colours"]) for r in ramps) * (cell + pad) + pad
    height = pad + len(ramps) * (cell + 22 + pad)
    img = Image.new("RGB", (width, height), ground)
    dr = ImageDraw.Draw(img)
    y = pad
    for r in ramps:
        dr.text((pad, y + cell // 2 - 6), r["name"], fill=ink, font=font)
        for i, c in enumerate(r["colours"]):
            x = label_w + i * (cell + pad)
            dr.rectangle([x, y, x + cell - 1, y + cell - 1], fill=tuple(c["rgb"]))
            dr.text((x, y + cell + 2), c["hex"][1:], fill=ink, font=font)
            dr.text((x, y + cell + 11), f"L{c['L']:.2f}", fill=dim, font=font)
        y += cell + 22 + pad
    img.save(path)


def write_images(ramps):
    draw_swatch(ramps, SWATCH)
    rgb = [tuple(c["rgb"]) for r in ramps for c in r["colours"]]
    Image.frombytes("RGB", (len(rgb), 1), bytes(v for c in rgb for v in c)).save(STRIP)
    print(f"wrote {os.path.relpath(STRIP, ROOT)} and {os.path.relpath(SWATCH, ROOT)}")


def main():
    with open(SRC) as f:
        ramps = json.load(f)["ramps"]
    out = ["#pragma once", "// ==== pal ====",
           "// The master palette as raylib Colors. GENERATED by tools/palette_header.py",
           "// from assets/palette.json - edit the JSON, re-run the tool, never this file.",
           "// Each ramp runs dark -> light from step 0. assets/palette_strip.png holds the",
           "// same colours in the same order (ramp after ramp), which is what the test",
           "// PaletteHeader.MatchesStrip compares against.", "",
           '#include "raylib.h"', "", "namespace pal {", ""]
    for r in ramps:
        n = len(r["colours"])
        out.append(f"inline constexpr int {r['name']}Steps = {n};")
        out.append(f"inline constexpr Color {r['name']}[{n}] = {{")
        for i, c in enumerate(r["colours"]):
            rr, g, b = c["rgb"]
            out.append(f"    Color{{{rr:3d}, {g:3d}, {b:3d}, 255}},  // {i:2d} {c['hex']}")
        out.append("};"); out.append("")
    total = sum(len(r["colours"]) for r in ramps)
    out.append(f"inline constexpr int totalColours = {total};")
    out.append("")
    out.append("// Every colour in strip order, for the conformance test and any future")
    out.append("// palette texture upload.")
    out.append("inline const Color* rampByIndex(int ramp, int& stepsOut) {")
    out.append("  switch (ramp) {")
    for i, r in enumerate(ramps):
        out.append(f"    case {i}: stepsOut = {r['name']}Steps; return {r['name']};")
    out.append("    default: stepsOut = 0; return nullptr;")
    out.append("  }")
    out.append("}")
    out.append(f"inline constexpr int rampCount = {len(ramps)};")
    out.append("")
    out.append("}  // namespace pal")
    with open(DST, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {os.path.relpath(DST, ROOT)}: {total} colours in {len(ramps)} ramps")
    write_images(ramps)


if __name__ == "__main__":
    main()
